#!/usr/bin/env bash
# ============================================================================
#  tunnel-launch.sh -- interactive launcher for tunnel.exe (Git Bash, Windows).
#
#  The engine has no --direct flag: the exit is Direct or WireGuard purely by
#  whether the settings file has a [wireguard] section. So "pick a mode" really
#  means "resolve a settings file for that mode", which is what this does --
#  including generating a Direct-mode file from a WireGuard one, with a
#  resolver that is actually reachable without the VPN.
#
#  Interactive:  ./tunnel-launch.sh
#  Scripted:     ./tunnel-launch.sh -s tunnel.toml --yes      (mode inferred)
#                ./tunnel-launch.sh --direct --yes            (file resolved)
#                ./tunnel-launch.sh --wg -s vpn.toml --log --yes
#
#  --direct / --wg   pick the exit mode
#  -s, --settings    settings file; mode is inferred from it if not given
#  -y, --yes         skip the confirmation prompt
#  --log, -v, --no-route   passed through to tunnel.exe
# ============================================================================

set -uo pipefail
shopt -s nullglob

c_bold=$'\033[1m'; c_dim=$'\033[2m'; c_red=$'\033[31m'; c_grn=$'\033[32m'
c_yel=$'\033[33m'; c_cyn=$'\033[36m'; c_off=$'\033[0m'

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

die()  { printf '%s %s\n' "${c_red}error:${c_off}" "$*" >&2; exit 1; }
warn() { printf '%s %s\n' "${c_yel}warn:${c_off}" "$*" >&2; }
hd()   { printf '\n%s\n' "${c_bold}$*${c_off}"; }

# --- discovery --------------------------------------------------------------

find_exe() {
  local c
  for c in "$script_dir/tunnel.exe" \
           "$script_dir/target/release/tunnel.exe" \
           "$script_dir/target/debug/tunnel.exe"; do
    [ -f "$c" ] && { printf '%s' "$c"; return 0; }
  done
  c="$(command -v tunnel.exe 2>/dev/null)" || return 1
  [ -n "$c" ] && { printf '%s' "$c"; return 0; }
  return 1
}

arch_dir() { case "$(uname -m)" in aarch64|arm64) echo arm64;; *) echo amd64;; esac; }

# The engine's own search order, so a pass here means a pass there. The last
# two candidates are relative to the WORKING directory, which we set to
# script_dir at launch -- that is why bin/<arch>/wintun.dll counts.
find_wintun() {
  local exe_dir="$1" a c
  a="$(arch_dir)"
  for c in "$exe_dir/wintun.dll" "$exe_dir/$a/wintun.dll" "$exe_dir/bin/$a/wintun.dll" \
           "$script_dir/bin/$a/wintun.dll" "$script_dir/wintun.dll"; do
    [ -f "$c" ] && { printf '%s' "$c"; return 0; }
  done
  return 1
}

# --- settings inspection ----------------------------------------------------

# An uncommented [wireguard] table is the whole difference between the modes.
has_wg() { grep -qE '^[[:space:]]*\[wireguard\]' "$1" 2>/dev/null; }

# First uncommented value of a key. Handles quoted and bare values, and strips
# a trailing # comment.
field() {
  sed -n -E "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\"?([^\"#]*)\"?.*/\1/p" "$2" 2>/dev/null \
    | head -1 | sed -E 's/[[:space:]]+$//'
}

# A resolver inside RFC1918 is almost always the VPN's own -- reachable through
# a WireGuard exit, a black hole under Direct. Worth catching before the engine
# pins it to the TUN and name resolution quietly stops.
is_private_dns() {
  case "$1" in
    10.*|192.168.*) return 0 ;;
    172.1[6-9].*|172.2[0-9].*|172.3[01].*) return 0 ;;
    *) return 1 ;;
  esac
}

describe() {
  local f="$1" dns ep
  dns="$(field dns "$f")"; ep="$(field endpoint "$f")"
  if has_wg "$f"; then
    printf 'WireGuard -> %s  (dns %s)' "${ep:-?}" "${dns:-default}"
  else
    printf 'Direct              (dns %s)' "${dns:-default}"
  fi
}

list_tomls() {
  local f
  for f in "$script_dir"/*.toml; do
    case "$(basename "$f")" in Cargo.toml|*.example.toml) continue ;; esac
    printf '%s\n' "$f"
  done
}

# Write a Direct-mode settings file from `src`: drop the [wireguard] table
# (and with it port_forward, which is meaningless without a remote exit) and
# force a resolver that works without the VPN.
make_direct() {
  local src="$1" out="$2" dns="$3"
  {
    printf '# Generated by tunnel-launch.sh from %s -- Direct exit.\n' "$(basename "$src")"
    printf '# No [wireguard] section, so the engine egresses out the host uplink.\n\n'
    awk -v dns="$dns" '
      # Drop the [wireguard] table: from its header to the next table or EOF.
      /^[[:space:]]*\[wireguard\]/ { skip = 1; next }
      skip && /^[[:space:]]*\[/    { skip = 0 }
      skip                          { next }
      # Replace dns, then swallow the comment lines that trailed the old value --
      # they describe a resolver this file no longer uses.
      /^[[:space:]]*dns[[:space:]]*=/ { print "dns = \"" dns "\""; seen = 1; trim = 1; next }
      trim && /^[[:space:]]*#/        { next }
      { trim = 0; print }
      END { if (!seen) print "dns = \"" dns "\"" }
    ' "$src"
  } > "$out" || return 1
  # Trim the blank tail the stripped table leaves behind.
  printf '%s\n' "$(cat "$out")" > "$out"
}

# --- launch -----------------------------------------------------------------

is_elevated() { net session >/dev/null 2>&1; }

# Values go through the environment, never through the -Command string: the
# command PowerShell parses is a fixed literal, so a path with spaces, quotes
# or an ampersand cannot break (or rewrite) it.
launch() {
  local exe="$1" workdir="$2"; shift 2
  local a quoted=()
  for a in "$@"; do
    case "$a" in *\ *) quoted+=("\"$a\"") ;; *) quoted+=("$a") ;; esac
  done

  if is_elevated; then
    printf '%s\n' "${c_dim}running in this terminal (already elevated)${c_off}"
    ( cd "$workdir" && "$exe" "$@" )
    return $?
  fi

  export TL_EXE TL_DIR TL_ARGS
  TL_EXE="$(cygpath -w "$exe")"
  TL_DIR="$(cygpath -w "$workdir")"
  TL_ARGS="${quoted[*]}"
  printf '%s\n' "${c_dim}not elevated -- requesting UAC; the engine opens in its own window${c_off}"
  powershell.exe -NoProfile -Command \
    'Start-Process -FilePath $env:TL_EXE -ArgumentList $env:TL_ARGS -Verb RunAs -WorkingDirectory $env:TL_DIR'
}

# --- argument parsing -------------------------------------------------------

mode=""; preset=""; assume_yes=0; extra=()
while [ $# -gt 0 ]; do
  case "$1" in
    --direct)  mode="direct" ;;
    --wg)      mode="wg" ;;
    -s|--settings) shift; preset="${1:-}"; [ -n "$preset" ] || die "-s needs a path" ;;
    -y|--yes)  assume_yes=1 ;;
    --log|--no-route|-v|--verbose) extra+=("$1") ;;
    -h|--help)
      awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "${BASH_SOURCE[0]}"
      exit 0 ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

# A settings file names its own mode -- the [wireguard] section IS the mode --
# so asking for one is only necessary when no file was given.
if [ -n "$preset" ] && [ -z "$mode" ]; then
  [ -f "$preset" ] || die "settings file not found: $preset"
  has_wg "$preset" && mode="wg" || mode="direct"
fi

# ============================================================================

exe="$(find_exe)" || die "tunnel.exe not found. Build it first:  cargo build --release"
exe_dir="$(dirname "$exe")"

hd "tunnel launcher"
printf '  engine   %s\n' "$exe"
if dll="$(find_wintun "$exe_dir")"; then
  printf '  wintun   %s\n' "$dll"
else
  warn "wintun.dll not found -- the engine will refuse to start."
  printf '           fix:  cp bin/%s/wintun.dll %s/\n' "$(arch_dir)" "$exe_dir"
fi

# --- mode -------------------------------------------------------------------

if [ -z "$mode" ]; then
  [ -t 0 ] || die "not a terminal; pass --direct or --wg <file>"
  hd "exit mode"
  printf '  1) WireGuard  -- all traffic egresses through your VPN peer\n'
  printf '  2) Direct     -- transparent proxy out your own uplink\n'
  while :; do
    read -r -p "select [1/2]: " a
    case "$a" in 1) mode="wg"; break ;; 2) mode="direct"; break ;; esac
  done
fi

# --- settings file ----------------------------------------------------------

settings=""

pick_from() {  # $1 = "wg" | "direct"
  local want="$1" f cands=() i=1
  while IFS= read -r f; do
    if [ "$want" = "wg" ]; then has_wg "$f" && cands+=("$f")
    else has_wg "$f" || cands+=("$f"); fi
  done < <(list_tomls)

  [ ${#cands[@]} -eq 0 ] && return 1
  # Display goes to stderr: this function's STDOUT is its return value, and a
  # caller doing settings="$(pick_from ...)" would otherwise capture the menu.
  hd "settings file" >&2
  for f in "${cands[@]}"; do
    printf '  %d) %-24s %s\n' "$i" "$(basename "$f")" "${c_dim}$(describe "$f")${c_off}" >&2
    i=$((i + 1))
  done
  printf '  p) type a path\n' >&2
  while :; do
    read -r -p "select: " a
    if [ "$a" = "p" ]; then
      read -r -p "path: " a
      [ -f "$a" ] && { printf '%s' "$a"; return 0; }
      printf '%s\n' "${c_red}no such file${c_off}" >&2
    elif [ "$a" -ge 1 ] 2>/dev/null && [ "$a" -le ${#cands[@]} ]; then
      printf '%s' "${cands[$((a - 1))]}"; return 0
    fi
  done
}

if [ -n "$preset" ]; then
  [ -f "$preset" ] || die "settings file not found: $preset"
  settings="$preset"
elif [ "$mode" = "wg" ]; then
  settings="$(pick_from wg)" || die \
    "no settings file with a [wireguard] section in $script_dir.
       Create one:  $exe init  then paste your provider's WireGuard fields."
else
  settings="$(pick_from direct)"
  if [ -z "$settings" ]; then
    # No Direct file exists. Offer to derive one from a WireGuard file rather
    # than make the user hand-edit a copy.
    src="$(list_tomls | head -1)"
    [ -n "$src" ] || die "no settings file found. Run:  $exe init"
    out="$script_dir/tunnel-direct.toml"
    hd "no Direct settings file"
    printf '  Generate %s from %s?\n' "$(basename "$out")" "$(basename "$src")"
    printf '  %s\n' "${c_dim}drops [wireguard] and sets a resolver reachable without the VPN${c_off}"
    read -r -p "resolver [1.1.1.1]: " d; d="${d:-1.1.1.1}"
    make_direct "$src" "$out" "$d" || die "could not write $out"
    printf '  %swrote %s%s\n' "$c_grn" "$out" "$c_off"
    settings="$out"
  fi
fi

# --- validate ---------------------------------------------------------------

if [ "$mode" = "wg" ] && ! has_wg "$settings"; then
  die "$(basename "$settings") has no [wireguard] section -- it would run as Direct."
fi
if [ "$mode" = "direct" ] && has_wg "$settings"; then
  die "$(basename "$settings") has a [wireguard] section -- it would run as WireGuard."
fi

dns="$(field dns "$settings")"
if [ "$mode" = "direct" ] && [ -n "$dns" ] && is_private_dns "$dns"; then
  warn "dns = $dns is a private address. Under a Direct exit there is nothing to
       reach it, and the engine pins it to the TUN -- name resolution will stop."
fi

# --- options ----------------------------------------------------------------

if [ ${#extra[@]} -eq 0 ] && [ -t 0 ] && [ "$assume_yes" -eq 0 ]; then
  hd "options"
  read -r -p "write a log transcript?    [y/N] " a; [ "${a,,}" = y ] && extra+=(--log)
  read -r -p "verbose logging?           [y/N] " a; [ "${a,,}" = y ] && extra+=(-v)
  read -r -p "capture the default route? [Y/n] " a; [ "${a,,}" = n ] && extra+=(--no-route)
fi

# --- confirm and go ---------------------------------------------------------

settings_abs="$(cd "$(dirname "$settings")" && pwd)/$(basename "$settings")"

hd "about to run"
printf '  exit       %s\n' "$(describe "$settings")"
printf '  settings   %s\n' "$settings_abs"
printf '  workdir    %s\n' "$script_dir"
printf '  command    %s %s %s\n' "$(basename "$exe")" "$(basename "$settings")" "${extra[*]-}"
for a in ${extra[@]+"${extra[@]}"}; do
  [ "$a" = "--no-route" ] && printf '  %s\n' \
    "${c_yel}--no-route: nothing is captured, no kill switch, no tripwire. Not a tunnel.${c_off}"
done

if [ "$assume_yes" -eq 0 ]; then
  [ -t 0 ] || die "not a terminal; pass --yes to skip confirmation"
  read -r -p $'\nstart? [y/N] ' a
  [ "${a,,}" = y ] || { printf 'cancelled\n'; exit 0; }
fi

launch "$exe" "$script_dir" "$settings_abs" ${extra[@]+"${extra[@]}"}
